### ISSUE TITLE
Aliases for frm, whr, ret, ins, etc 

### ISSUE THREAD

**Issue by scf4** [lusakasa/sqorn#3]
I’m a little put off by the naming convention here. It doesn’t seem very JS-like to me, and it makes it harder to remember the function names, all to save a few characters. 

It would make more sense (to me) to have these short versions as optional aliases. 

I hope this doesn’t sound too critical and you’ve obviously put a lot of work into this project, but I’m on the lookout for something to replace Knex, and so far the naming convention is a deal-killer to me. 

Thanks!

**Comment by eejdoowad** [comment]
This seems to be a very popular opinion. I'll be switching all method names to full sql clause names. E.g. .frm -> from, .whr -> .where

**Comment by scf4** [comment]
@eejdoowad Thanks for the quick response, and for listening to the community! I look forward to see how this project turns out.

**Comment by eejdoowad** [comment]
Implemented and published in Sqorn v0.0.15
