### ISSUE TITLE
Automatically camelcases existing `node-pg`

### ISSUE THREAD

**Issue by tuckerconnelly** [lusakasa/sqorn#38]
The global monkeypatch in `sqorn-pg` makes this unusable for us :( we want to slowly migrate to this from `node-pg`, with our normal `snake_case`, but the forced `camelCase` is holding us back.

**Comment by eejdoowad** [comment]
Making that configurable is on the list of Todos for version 1.  You'll probably specify an option when initializing the connection. Initialization will likely be modified to something like this:

```js
const sqorn = require('sqorn-pg')
const pg = require('pg')

const pool = new pg.Pool()
const sq = sqorn({ pg, pool, convertCase: false })
```

**Comment by eejdoowad** [comment]
I ended up removing the monkey patch in favor of row transformations.

Sqorn v.0.0.38, lets you configure key transformations with [mapInputKeys](https://sqorn.org/docs/tutorial.html#map-input-keys) and [mapOutputKeys](https://sqorn.org/docs/tutorial.html#map-output-keys). These transformations only affect queries executed through their query builder instance.
