### ISSUE TITLE
0.0.36 update doesn't work out of the box, reports missing `sqorn-adapter-pg`

### ISSUE THREAD

**Issue by drulia** [lusakasa/sqorn#41]
After updating to 0.0.36 app wont start and reports missing `sqorn-adapter-pg`.
Sqorn [Demo](https://sqorn.org/demo.html) page is also broken at the moment and is reporting same error.

**Comment by eejdoowad** [comment]
I missed adding that dependency to the sqorn-pg package. It's resolved in v0.0.37. Thanks
